# -*- coding: utf-8 -*-
"""Creating initial schema

Revision ID: 7b59f7c87c5d
Revises: 
Create Date: 2016-02-26 11:37:02.952857

"""

# revision identifiers, used by Alembic.

revision = '7b59f7c87c5d'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import UserDefinedType

class ISBN(UserDefinedType):
    def get_col_spec(self):
        return "isbn13"

    def bind_processor(self, dialect):
        def process(value):
            return value
        return process

    def result_processor(self, dialect, coltype):
        def process(value):
            return value
        return process

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'books',
        sa.Column('isbn', ISBN, primary_key=True),
        sa.Column('title', sa.Text, nullable=False),
        sa.Column('author', sa.Text, nullable=False))

    op.create_table(
        'loans',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('isbn', ISBN, sa.ForeignKey('books.isbn'), nullable=False),
        sa.Column('borrower', sa.Text, nullable=False),
        sa.Column('borrowed_at', sa.DateTime, nullable=False, server_default=sa.func.current_timestamp()),
        sa.Column('returned_at', sa.DateTime),
    )

    books = sa.table('books',
                     sa.Column('isbn', ISBN, primary_key=True),
                     sa.Column('title', sa.Text, nullable=False),
                     sa.Column('author', sa.Text, nullable=False))

    op.bulk_insert(books,
                   [
                       {
                           "title": "Functional Programming in Scala",
                           "author": "Paul Chiusano and Rúnar Bjarnason",
                           "isbn": "978-1-61729-065-7"
                       },
                       {
                           "title": "Beginner's Finnish",
                           "author": "Agi Risko",
                           "isbn": "978-0-7818-1024-1"
                       },
                       {
                           "title": "100 Words for Lovers",
                           "author": "Editors of the American Heritage Dictionaries",
                           "isbn": "978-0-547-21257-9"
                       },

                   ])

    loans = sa.table('loans',
                     sa.Column('id', sa.Integer, primary_key=True),
                     sa.Column('isbn', ISBN, sa.ForeignKey('books.isbn'), nullable=False),
                     sa.Column('borrower', sa.Text, nullable=False),
                     sa.Column('borrowed_at', sa.DateTime, nullable=False, server_default=sa.func.current_timestamp()),
                     sa.Column('returned_at', sa.DateTime))
    op.bulk_insert(loans,
                   [
                       {
                           "isbn": "978-1-61729-065-7",
                           "borrower": "Max Spolaor <mspolaor@nrao.edu>",
                           "borrowed_at": "2015-11-04 00:00:00.000000",
                           "returned_at": "2015-11-09 16:57:15.984812"
                       },
                       {
                           "isbn": "978-1-61729-065-7",
                           "borrower": "Max Spolaor <mspolaor@nrao.edu>",
                           "borrowed_at": "2015-11-04 00:00:00.000000",
                           "returned_at": "2015-11-09 16:57:15.984812"
                       },
                       {
                           "isbn": "978-1-61729-065-7",
                           "borrower": "Max Spolaor <mspolaor@nrao.edu>",
                           "borrowed_at": "2015-11-04 00:00:00.000000",
                           "returned_at": "2015-11-09 16:57:15.984812"
                       }
                   ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    op.drop_table('books')
    ### end Alembic commands ###
